# Generated by Django 5.2.1 on 2025-06-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centauri", "0003_alter_astronomyshow_description"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("seat", "row", "show_session"),
                name="unique_ticket_seat_row_show_session",
            ),
        ),
    ]
