# Generated by Django 5.2.1 on 2025-06-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centauri", "0004_ticket_unique_ticket_seat_row_show_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="planetariumdome",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="showtheme",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
