# Generated by Django 5.2.1 on 2025-06-06 16:49

import centauri.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "centauri",
            "0005_alter_astronomyshow_title_alter_planetariumdome_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="poster",
            field=models.ImageField(
                null=True, upload_to=centauri.models.astronomy_show_poster_path
            ),
        ),
    ]
