# Generated by Django 5.2.1 on 2025-06-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centauri", "0006_astronomyshow_poster"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="showsession",
            constraint=models.UniqueConstraint(
                fields=("planetarium_dome", "show_time"),
                name="unique_planetarium_dome_show_time",
            ),
        ),
    ]
